### ISSUE TITLE
Setting manifest is deprecated in puppet.conf

### ISSUE THREAD

**Issue by radiumx3** [rfkrocktk/docker-puppetmaster#17]
Warning: Setting manifest is deprecated in puppet.conf. See http://links.puppetlabs.com/env-settings-deprecations
   (at /usr/lib/ruby/vendor_ruby/puppet/settings.rb:1095:in `block in issue_deprecations')

Unable to start puppet because of this.

Puppet 4.x disallow setting manifest directly in the puppet.conf

**Comment by rfkrocktk** [comment]
You're building the image from scratch? 

Do you want Puppet 4? I didn't think it was out yet, last time I checked, the latest in the repo was 3.7.X.

**Comment by radiumx3** [comment]
Well i just used your own image step by step with tutorial, i'll check tommorow at work if by any chance you install the v 4.x instead of 3 but i didnt did any changes. Pulled it directly from docker registry.

**Comment by rfkrocktk** [comment]
The latest Puppet in their repository is 3.7.4. How did you experience this bug? Can you provide steps for me to reproduce?

**Comment by radiumx3** [comment]
Well i'm back home now, i'll reproduce tommorow and tell you more about it, all i can say now is that i stricly sticked to the tutorial from the beginning till the ssh connection, with which i struggled a bit, then i   installed docker-enter to enter the container and checked logs to see why the master wasn't starting, this is the error i've found so i supposed it's because of this. Not sure tho'

**Comment by radiumx3** [comment]
Tried again today, still same issue by just following tutorial (the ssh connection part is a bit undocumented tho` didnt managed to pass Permission Denied even if i added a key into that mounted file like the tuto states)

No time to test further we built our own container in the end. I'll just close there since i can't provide more about what's happening in details...
