### ISSUE TITLE
Please update to Puppet 3.8.2

### ISSUE THREAD

**Issue by mbirth** [rfkrocktk/docker-puppetmaster#18]
The Puppet 3.6.2 doesn't support `parser = future` and also doesn't support `$array.each |String $item| { ... }` constructs. Could you update the Dockerfile to the latest version, please?

I ran `apt-get upgrade` inside the docker image and after it upgraded to latest Passenger and latest Puppet 3.8.2, I had to make some changes to `/etc/nginx/sites-available/puppetmaster`:

```
-    passenger_set_cgi_param    HTTP_X_CLIENT_S_DN $ssl_client_s_dn; 
-    passenger_set_cgi_param    HTTP_X_CLIENT_VERIFY $ssl_client_verify; 
+    passenger_set_header       X_CLIENT_S_DN $ssl_client_s_dn; 
+    passenger_set_header       X_CLIENT_VERIFY $ssl_client_verify; 
```

Everything is working fine now.

**Comment by rfkrocktk** [comment]
Sure, I'll rebuild to latest available for the repositories.

**Comment by rfkrocktk** [comment]
@mbirth Did changes to Passenger force you to make those changes with the nginx configuration?

**Comment by mbirth** [comment]
@rfkrocktk: Yes, `passenger_set_cgi_param` has been replaced with `passenger_env_var` and `passenger_set_header`. Also, `passenger_set_header` adds `HTTP_` in front automatically.

**Comment by rfkrocktk** [comment]
Finishing up testing. FYI from now on, Docker image versions will reflect the version of the Puppet Master Debian package in semantic versioning format. For example, the next version tag will be v3.8.2, reflecting usage of that version of the Puppet Master and agent.

**Comment by rfkrocktk** [comment]
Updated and fixed with commit a488311a0454257b0b2c269c51811218fd8bf095. Publishing to Docker registry now.

**Comment by rfkrocktk** [comment]
Apologies for the delay getting it live to the Docker Hub. Docker Hub is having a lot of problems and all of my builds are failing due to stupid timeouts. https://hub.docker.com/r/rfkrocktk/puppetmaster/builds/bsbbfpxlwjy8mj97b6yiwhk/

Please remind me in a few days to retrigger the builds.

**Comment by mbirth** [comment]
Woohooo, awesome! :) Thanks a lot! I'll try to remind you. Have a great day!
