### ISSUE TITLE
Puppet Agent Certificate Request Not Working

### ISSUE THREAD

**Issue by gowthamsadasivam** [rfkrocktk/docker-puppetmaster#22]
Hi, 

While following along with the instructions from README from the repo. At step [Playing nice with others] (https://github.com/rfkrocktk/docker-puppetmaster#playing-nice-with-others) I got an issue as the output for signing the agent certificate is **Warning: Setting manifest is deprecated in puppet.conf. See http://links.puppetlabs.com/env-settings-deprecations
   (at /usr/lib/ruby/vendor_ruby/puppet/settings.rb:1141:in `issue_deprecation_warning')**

![Signing Agent Certificate] (http://i.imgur.com/pq1Sjxr.png)

I will have to manually log into the puppet node and invoke the puppet agent with **root@dockerduck:~# puppet agent --server ultramaster --waitforcert 60 --test** to make the certificate request to puppetmaster.

Any idea why this happens?

**Comment by rfkrocktk** [comment]
That's not a bug, it's a deprecation warning. I wanted to still support the old syntax, so the deprecation warning comes from the default configuration that ships from Puppet's own package from their Debian repository.

Refer to the Puppet docs about this. The problem you're reporting also happens with Puppet and a Puppet Master _outside_ of a container, it's just Puppet's policy for security. Puppet uses PKI, so every agent must have its own client-side SSL certificate that is signed by the CA that is hosted by the Puppet Master.
