### ISSUE TITLE
Why choose `phusion/baseimage` over `phusion/passenger-ruby22`?

### ISSUE THREAD

**Issue by kierr** [rfkrocktk/docker-puppetmaster#27]
What is the point in using `phusion/basimage` and going through all that configuration for nginx, passenger, and ruby... when `phusion/passenger-ruby22` has it all?

Was there a reason behind this choice?

**Comment by naftulikay** [comment]
See [rfkrocktk/docker-puppetserver](https://github.com/rfkrocktk/docker-puppetserver) for the latest Puppet Server.

The base image Docker image was chosen for its feature-set. I wasn't aware of the passenger image at the time.

**Comment by qafro1** [comment]
Hey

Is there any chance to update puppet to 4.5

**Comment by naftulikay** [comment]
See the comment right above yours.
