### ISSUE TITLE
Setting manifest is deprecated in puppet.conf

### ISSUE THREAD

**Issue by cohenaj194** [rfkrocktk/docker-puppetmaster#28]
Following the directions on the read me an issue occurs when trying to sign the cert for dockerduck. 

```
root@ultramaster:/# puppet cert list
Warning: Setting manifest is deprecated in puppet.conf. See http://links.puppetlabs.com/env-settings-deprecations
   (at /usr/lib/ruby/vendor_ruby/puppet/settings.rb:1141:in `issue_deprecation_warning')
root@ultramaster:/# puppet cert sign dockerduck.docker.com
Warning: Setting manifest is deprecated in puppet.conf. See http://links.puppetlabs.com/env-settings-deprecations
   (at /usr/lib/ruby/vendor_ruby/puppet/settings.rb:1141:in `issue_deprecation_warning')
Error: Could not find certificate request for dockerduck.docker.com
```

**Comment by naftulikay** [comment]
The warning you're seeing is not related to the error you're experiencing, please ignore it.

Nothing has connected to your master and therefore there's nothing to sign. Also, please if you can, start using `rfkrocktk/puppetserver` for Puppet Server 1 and 2. The Puppet Server 2 branch needs work, but Puppet Server 1 releases are working very well.
